///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: file_names

class ExerciseHubExercises {
/*
{
  "id": "1",
  "title": "5 Moves For Best Booty",
  "thumbnail": "https://raw.githubusercontent.com/codeifitech/fitness-app/master/thumbnails/active-adult-athlete-body-416778.jpg",
  "gif": "https://raw.githubusercontent.com/codeifitech/fitness-app/master/gif/5-moves-for-best-booty.gif",
  "seconds": "30"
}
*/

  String? id;
  String? title;
  String? thumbnail;
  String? gif;
  String? seconds;

  ExerciseHubExercises({
    this.id,
    this.title,
    this.thumbnail,
    this.gif,
    this.seconds,
  });
  ExerciseHubExercises.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    title = json["title"]?.toString();
    thumbnail = json["thumbnail"]?.toString();
    gif = json["gif"]?.toString();
    seconds = json["seconds"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["title"] = title;
    data["thumbnail"] = thumbnail;
    data["gif"] = gif;
    data["seconds"] = seconds;
    return data;
  }
}

class ExerciseHub {
/*
{
  "exercises": [
    {
      "id": "1",
      "title": "5 Moves For Best Booty",
      "thumbnail": "https://raw.githubusercontent.com/codeifitech/fitness-app/master/thumbnails/active-adult-athlete-body-416778.jpg",
      "gif": "https://raw.githubusercontent.com/codeifitech/fitness-app/master/gif/5-moves-for-best-booty.gif",
      "seconds": "30"
    }
  ]
}
*/

  List<ExerciseHubExercises?>? exercises;

  ExerciseHub({
    this.exercises,
  });
  ExerciseHub.fromJson(Map<String, dynamic> json) {
    if (json["exercises"] != null) {
      final v = json["exercises"];
      final arr0 = <ExerciseHubExercises>[];
      v.forEach((v) {
        arr0.add(ExerciseHubExercises.fromJson(v));
      });
      exercises = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (exercises != null) {
      final v = exercises;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["exercises"] = arr0;
    }
    return data;
  }
}
